### ISSUE TITLE
Ubuntu-latest workflows will use Ubuntu-20.04 soon

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/webservices-dispatch-action#10]
Saw the following show on in a re-rendering action. Linking it here for visibility. Feel free to close if no action is required.

> Ubuntu-latest workflows will use Ubuntu-20.04 soon. For more details, see https://github.com/actions/virtual-environments/issues/1816

**Comment by beckermr** [comment]
We run everything in docker here so nothing to worry about.

**Comment by jakirkham** [comment]
Thought so. Feel free to close then 🙂
