### ISSUE TITLE
Update PR title after `update version` commands

### ISSUE THREAD

**Issue by jaimergp** [conda-forge/webservices-dispatch-action#130]
I've been trying to update the PR title of the "conda forge admin update version" commands but I found a blocker that would require a bigger refactor and stopped there.

Basically I wanted to call this:

```python
def update_pr_title(
    repo_owner: str, repo_name: str, pr_number: int , found_version: str
) -> bool:
    try:
        gh = github.Github(os.environ["GH_TOKEN"])
        repo = gh.get_repo(f"{repo_owner}/{repo_name}")
        pr = repo.get_pull(pr_number)
    except Exception:
        LOGGER.exception(
            "error while trying to get PR title for %s/%s#%s",
            repo_owner,
            repo_name,
            pr_number,
        )
        return False
    if pr.title == "ENH: update package version":  # user didn't change the default
        try:
            pr.edit(title=f"{pr.title} to {found_version}")
        except Exception:
            LOGGER.exception(
                "error while trying to change PR title for %s/%s#%s",
                repo_owner,
                repo_name,
                pr_number,
            )
            return False
    return True
```

right after 

https://github.com/conda-forge/webservices-dispatch-action/blob/7b13ec3da8da6b42ecd76f80b755da1308218b67/webservices_dispatch_action/version_updater.py#L167-L175

But that involves calling GH_TOKEN dependent code, and we can't do that due to the hardening? I thought maybe we can do it over here instead:

https://github.com/conda-forge/webservices-dispatch-action/blob/7b13ec3da8da6b42ecd76f80b755da1308218b67/webservices_dispatch_action/__main__.py#L211-L215

But we aren't returning the found version from the subcommand call (maybe we could return via JSON payloads?), so we wouldn't know what to change the PR title to. 

Am I overthinking this or can we just call `Github()` stuff inside `version_updater.py`?

**Comment by beckermr** [comment]
All of the code that deals with recipes is in a docker container. We are free to use the GH token in main.py.
