### ISSUE TITLE
Rerendering failing (maybe `.conda` related) 

### ISSUE THREAD

**Issue by jakirkham** [conda-forge/webservices-dispatch-action#18]
Tried re-rendering recently ( https://github.com/conda-forge/scalene-feedstock/pull/11#issuecomment-1319188637 ), but the bot ran into an error ( https://github.com/conda-forge/scalene-feedstock/pull/11#issuecomment-1319189988 ). From [the log]( https://github.com/conda-forge/scalene-feedstock/actions/runs/3491923860/jobs/5845126109 ) (also [attached]( https://github.com/conda-forge/webservices-dispatch-action/files/10035580/scalene_11_rerender_log.txt )) am seeing this issue

```python
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmp0ws_5enf
bsdtar: Failed to set default locale
Traceback (most recent call last):
  File "/opt/conda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 670, in main
    args.subcommand_func(args)
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 486, in __call__
    self._call(args, tmpdir)
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 491, in _call
    configure_feedstock.main(
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2213, in main
    exclusive_config_file, cf_pinning_ver = get_cfp_file_path(
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2039, in get_cfp_file_path
    assert os.path.exists(cf_pinning_file)
```

**Comment by jakirkham** [comment]
For more context, in conda-smithy we have [this line]( https://github.com/conda-forge/conda-smithy/blob/6de36e002b2d7982d77d4baa2a30e7001a4152ef/conda_smithy/configure_feedstock.py#L2019 ), which relies on getting a `.tar.bz2` file of `conda-forge-pinning`. However as we enabled `.conda` everywhere and a `conda-forge-pinning` change ( https://github.com/conda-forge/conda-forge-pinning-feedstock/commit/eb391bb477cd0d35e3c038a837085149f9519e2c ) triggered [a `.conda` package to built & uploaded]( https://app.travis-ci.com/github/conda-forge/conda-forge-pinning-feedstock/builds/257927991#L728 ), this caused the re-rendering to start failing due to the `.conda` package not working with `conda-smithy`.

After discussion offline, we deleted the `.conda` package of `conda-forge-pinning` and rolled `conda-forge-pinning` back to `.tar.bz2` ( https://github.com/conda-forge/conda-forge-pinning-feedstock/commit/f67a3b2bc0e04845b6f80cbfc8c8ba521c488524 ). This should ensure that `.tar.bz2` packages are only produced by `conda-forge-pinning` until we can fix `conda-smithy` and retry. We also tested that things are now working with the re-rendering bot ( https://github.com/conda-forge/scalene-feedstock/pull/11#issuecomment-1319200205 ).

**Comment by jakirkham** [comment]
Filing issue ( https://github.com/conda-forge/conda-smithy/issues/1692 ) for following up on conda-smithy. Closing this as resolved

**Comment by jakirkham** [comment]
This seems to be reoccurring. In particular am seeing an old `conda-smithy` installed during re-rendering. Please see [this GH Actions job]( https://github.com/conda-forge/sh-feedstock/actions/runs/3568372742/jobs/5997167806 ) for details (snippet below):

```python
INFO:conda_smithy.configure_feedstock:conda-smithy version (3.15.1) is out-of-date (3.22.0) in conda-smithy's environment.
INFO:conda_smithy.configure_feedstock:Downloading conda-forge-pinning-2022.11.27.15.56.36
INFO:conda_smithy.configure_feedstock:Extracting conda-forge-pinning to /tmp/tmpwxe9oa00
bsdtar: Failed to set default locale
Traceback (most recent call last):
  File "/opt/conda/bin/conda-smithy", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 681, in main
    args.subcommand_func(args)
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 486, in __call__
    self._call(args, tmpdir)
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/cli.py", line 491, in _call
    configure_feedstock.main(
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 2160, in main
    exclusive_config_file, cf_pinning_ver = get_cfp_file_path(
  File "/opt/conda/lib/python3.8/site-packages/conda_smithy/configure_feedstock.py", line 1986, in get_cfp_file_path
    assert os.path.exists(cf_pinning_file)
AssertionError
```

Edit: Hmm...seems closing and reopening the associated PR fixed the issue

**Comment by beckermr** [comment]
We can maybe add a pin to prevent old smithy versions?

**Comment by jakirkham** [comment]
Looking earlier in the log, it did try to update `conda-smithy`, but we got a corrupted package (likely bad download). As a result the update never occurred.

```sh
error    Error opening for reading "/opt/conda/pkgs/python-3.8.12-hf930737_2_cpython.tar.bz2": No such file or directory
error    File not valid: SHA256 sum doesn't match expectation "/opt/conda/pkgs/python-3.8.12-hf930737_2_cpython.tar.bz2"
    Expected: 9bb9860cdd4e823ffc56809cf01758528f66e615516b27f2adcfe358dcb45ec9
    Actual: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
```

Is there some image that we are using here? Perhaps we could rebuild that image, which would ensure we have a new enough `conda-smithy` to start

**Comment by beckermr** [comment]
Yes we can rebuild the image.

**Comment by jakirkham** [comment]
Might also be worthwhile to update the Python version used here ( ~https://github.com/conda-forge/webservices-dispatch-action/pull/19~ https://github.com/conda-forge/webservices-dispatch-action/pull/20 )

**Comment by jakirkham** [comment]
What do you think about making this run on a cron job? Maybe once weekly like how other Docker image builds are done?

**Comment by beckermr** [comment]
Sure.

**Comment by jakirkham** [comment]
> > What do you think about making this run on a cron job? Maybe once weekly like how other Docker image builds are done?
>
> Sure.

Handling in PR ( https://github.com/conda-forge/webservices-dispatch-action/pull/21 )

**Comment by jakirkham** [comment]
The Docker image has been rebuilt. It also includes a minimum bound on `conda-smithy` to ensure `>= 3.22.0` is installed. The `python` version has also been bumped to `3.10`. Additionally a cron job has been added to rebuild the image once a week. This should hopefully keep things fresh here and thus avoid similar issues in the future.
