### ISSUE TITLE
Need a message if the GitHub Actions files cannot be updated

### ISSUE THREAD

**Issue by njzjz** [conda-forge/webservices-dispatch-action#50]
When the GitHub Actions files need to be updated, and the web service action doesn't have permission, it doesn't give any messages. The contributors may easily ignore the fact that they should rerender and push the repository locally.

Ideally, a comment should be made in this case, notifying the contributors that they need to update these files manually.

xref: https://github.com/conda-forge/pytorch-cpu-feedstock/pull/224#issuecomment-1994975034

**Comment by beckermr** [comment]
Right. We just reject the changes so it works but we should post a message on the PR.

**Comment by jakirkham** [comment]
Yeah it might be worth putting in the docs and then the message can link to the docs

**Comment by jakirkham** [comment]
Where in the code do we reject the changes?

**Comment by beckermr** [comment]
We have to or the push to the repo fails. It is in main maybe? Or in the rerender model

**Comment by jakirkham** [comment]
Sorry, understand why

Was asking where (in the code)

Trying to figure out where we can make the GH comment happen

**Comment by njzjz** [comment]
Here,

https://github.com/conda-forge/webservices-dispatch-action/blob/bb41922e55d365408622fa1810f971682423c9b1/webservices_dispatch_action/rerendering.py#L38-L46

**Comment by beckermr** [comment]
We can add a comment to the rerender error.

**Comment by beckermr** [comment]
closed by https://github.com/conda-forge/webservices-dispatch-action/pull/51
